services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./models:/app/models:rw
      - ./data:/app/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - MODELS_DIR=/app/models
      - DATA_DIR=/app/data
    depends_on:
      - tensorflow

  tensorflow:
    container_name: tensorflow
    image: tensorflow/tensorflow:latest
    volumes:
      - ./models:/models:rw
      - ./data:/data:rw
    command: >
      /bin/bash -c "
        pip install --no-cache-dir --user pandas numpy scikit-learn &&
        tail -f /dev/null
      "
    environment:
      - PYTHONUNBUFFERED=1
      - PIP_NO_CACHE_DIR=1
    user: root
