spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: jdbc:postgresql://localhost:5432/bit
    username: postgres
    password: ivan02082004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:/changelog/db.changelog-master.yaml
    enabled: true
yandex:
  disk:
    access-token: y0_AgAAAABkNd0xAAzshgAAAAEbpHpPAACO2BjhGwJBX6OIkfOIQ68IXZDiag
server:
  port: 8080